// ─────────────────────────────────────────────────────────────
// Oceanvs Acquisition CRM — Norway Sauna Operator Database
// 69 operators. Contact data enriched where found.
// ─────────────────────────────────────────────────────────────

import { SaunaOperator } from '@/types/crm'

export const SAUNA_OPERATORS: SaunaOperator[] = [
  // ── EASTERN NORWAY — OSLO ──────────────────────────────────
  {
    id: 'kok-oslo',
    vertical: 'sauna',
    name: 'KOK Oslo',
    region: 'Eastern Norway',
    subRegion: 'Oslo',
    type: 'Commercial',
    format: 'Floating sauna boat',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — Oslofjord',
    priceRange: '320–3,700 NOK',
    bookingModel: 'Drop-in + Private hire',
    yearEst: 'c.2018',
    notes: 'Two sites: Langkaia (Opera) & Aker Brygge. Wood-fired. Sauna cruise option.',
    website: 'koknorge.no',
    isMultiSite: true,
    priority: 'high',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['multi-site', 'floating', 'premium', 'oslo', 'brand'],
    estimatedValuation: 'EUR 3–6M',
    contact: {
      email: 'bedrift@koknorge.no',
      phone: '+47 934 00 522',
      address: 'C/O Mesh, Tordenskiolds gate 2, 0160 Oslo',
      contactSource: 'website',
    },
  },
  {
    id: 'oslo-badstuforening',
    vertical: 'sauna',
    name: 'Oslo Badstuforening',
    region: 'Eastern Norway',
    subRegion: 'Oslo (multiple)',
    type: 'Association / Non-profit',
    format: 'Floating raft (multiple units)',
    ownershipModel: 'Non-profit',
    waterAccess: 'Yes — Oslofjord',
    priceRange: '125–260 NOK',
    bookingModel: 'Drop-in (members + public)',
    yearEst: '2016',
    notes: '6–7 locations incl. Sukkerbiten, Langkaia. Trosten unit won TIME Greatest Places 2025.',
    website: 'oslobadstuforening.no',
    isMultiSite: true,
    priority: 'low',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['non-profit', 'floating', 'multi-site', 'oslo'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'salt-sauna',
    vertical: 'sauna',
    name: 'SALT Sauna',
    region: 'Eastern Norway',
    subRegion: 'Oslo',
    type: 'Commercial',
    format: 'Land-based (12 saunas, waterfront)',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — Oslofjord',
    priceRange: '205–1,990 NOK',
    bookingModel: 'Drop-in + Private hire',
    yearEst: 'c.2019',
    notes: '12 saunas; capacities 4–100 ppl. Cultural venue with bar/music. Festival atmosphere.',
    website: 'salted.no',
    isMultiSite: false,
    priority: 'high',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['land-based', 'premium', 'oslo', 'large-capacity', 'cultural'],
    estimatedValuation: 'EUR 4–8M',
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'bademaschinen',
    vertical: 'sauna',
    name: 'Bademaschinen',
    region: 'Eastern Norway',
    subRegion: 'Oslo',
    type: 'Commercial',
    format: 'Floating (glass-sided)',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — Oslofjord',
    priceRange: '250–350 NOK',
    bookingModel: 'Drop-in + Private hire',
    yearEst: 'c.2019',
    notes: 'Architecturally distinctive glass structure. Oslo waterfront.',
    website: '',
    isMultiSite: false,
    priority: 'medium',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'design', 'oslo'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'oslo-fjord-sauna',
    vertical: 'sauna',
    name: 'Oslo Fjord Sauna (FjordCleanUP)',
    region: 'Eastern Norway',
    subRegion: 'Oslo — Sørenga',
    type: 'Social enterprise',
    format: 'Floating (2 units)',
    ownershipModel: 'Social enterprise',
    waterAccess: 'Yes — Oslofjord',
    priceRange: '~200 NOK',
    bookingModel: 'Drop-in',
    yearEst: '2021',
    notes: 'Huginn & Muninn units. Proceeds fund seabed litter removal.',
    website: 'fjordcleanup.no',
    isMultiSite: false,
    priority: 'low',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'social-enterprise', 'oslo', 'eco'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'greenboats',
    vertical: 'sauna',
    name: 'GreenBoats',
    region: 'Eastern Norway',
    subRegion: 'Oslo',
    type: 'Commercial',
    format: 'Floating (solar-powered)',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — Oslofjord',
    priceRange: '~300 NOK',
    bookingModel: 'Private hire',
    yearEst: 'c.2021',
    notes: 'Solar-powered. Eco positioning.',
    website: '',
    isMultiSite: false,
    priority: 'medium',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'eco', 'oslo', 'solar'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'fjordtokt',
    vertical: 'sauna',
    name: 'Fjordtokt Båt & Badstu',
    region: 'Eastern Norway',
    subRegion: 'Oslo',
    type: 'Commercial',
    format: 'Floating (mobile sauna cruise)',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — Oslofjord',
    priceRange: '~500+ NOK',
    bookingModel: 'Private hire (cruise format)',
    yearEst: 'c.2020',
    notes: 'Sail-and-sauna format; not stationary.',
    website: '',
    isMultiSite: false,
    priority: 'medium',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'cruise', 'oslo', 'mobile'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'kongen-marina',
    vertical: 'sauna',
    name: 'Kongen Marina',
    region: 'Eastern Norway',
    subRegion: 'Oslo — Frognerkilen',
    type: 'Commercial',
    format: 'Land-based (dome + glass sauna)',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — Oslofjord',
    priceRange: 'Members + guests',
    bookingModel: 'Members + guests',
    yearEst: 'c.2022',
    notes: 'Dome sauna + 360° glass sauna. Miami-style beach club setting.',
    website: 'kongenmarina.no',
    isMultiSite: false,
    priority: 'medium',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['land-based', 'premium', 'oslo', 'beach-club', 'members'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'sagene-folkebad',
    vertical: 'sauna',
    name: 'Sagene Folkebad',
    region: 'Eastern Norway',
    subRegion: 'Oslo — Grünerløkka',
    type: 'Association / Non-profit',
    format: 'Land-based (historic bathhouse)',
    ownershipModel: 'Non-profit (Oslo Badstuforening)',
    waterAccess: 'No — cold plunge pool only',
    priceRange: '~150–220 NOK',
    bookingModel: 'Drop-in',
    yearEst: '2025 (reopened)',
    notes: 'Historic 1899 building. 42-seat sauna, 12.5m pool, cold plunge. Phone-free zone.',
    website: 'oslobadstuforening.no',
    isMultiSite: false,
    priority: 'low',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['land-based', 'non-profit', 'oslo', 'historic'],
    contact: { contactSource: 'research_needed' },
  },
  // ── EASTERN NORWAY — VESTFOLD ──────────────────────────────
  {
    id: 'son-spa',
    vertical: 'sauna',
    name: 'Son Spa Sauna Rafts',
    region: 'Eastern Norway',
    subRegion: 'Son, Viken',
    type: 'Commercial',
    format: 'Floating raft',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — Oslofjord',
    priceRange: '~300–500 NOK',
    bookingModel: 'Private hire',
    yearEst: 'c.2020',
    notes: 'Popular day-trip from Oslo. Busy summer season.',
    website: '',
    isMultiSite: false,
    priority: 'medium',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'oslofjord', 'vestfold'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'aasgaardstrand',
    vertical: 'sauna',
    name: 'Aasgaardstrand Badeselskab',
    region: 'Eastern Norway',
    subRegion: 'Åsgårdstrand, Vestfold',
    type: 'Association / Non-profit',
    format: 'Land-based (barrel, harbourside)',
    ownershipModel: 'Non-profit',
    waterAccess: 'Yes — Oslofjord',
    priceRange: '~100–150 NOK',
    bookingModel: 'Drop-in + members',
    yearEst: 'Est.',
    notes: 'Active bathing association. Direct harbour access.',
    website: '',
    isMultiSite: false,
    priority: 'low',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['land-based', 'non-profit', 'vestfold'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'holmestrand',
    vertical: 'sauna',
    name: 'Holmestrand Fjordbadstu',
    region: 'Eastern Norway',
    subRegion: 'Holmestrand, Vestfold',
    type: 'Commercial',
    format: 'Floating',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — Oslofjord',
    priceRange: '~250–400 NOK',
    bookingModel: 'Private hire',
    yearEst: 'c.2021',
    notes: 'Inner Oslofjord / Vestfold coast.',
    website: '',
    isMultiSite: false,
    priority: 'medium',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'vestfold'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'sjobadet-tonsberg',
    vertical: 'sauna',
    name: 'Sjøbadet Badstue (Tønsberg)',
    region: 'Eastern Norway',
    subRegion: 'Tønsberg, Vestfold',
    type: 'Commercial',
    format: 'Floating / land-based waterfront',
    ownershipModel: 'Private company',
    waterAccess: 'Yes',
    priceRange: '~250 NOK',
    bookingModel: 'Drop-in + Private hire',
    yearEst: 'c.2021',
    notes: 'Tønsberg harbour.',
    website: '',
    isMultiSite: false,
    priority: 'medium',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'vestfold', 'tønsberg'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'flyt-stavern',
    vertical: 'sauna',
    name: 'FLYT Stavern',
    region: 'Eastern Norway',
    subRegion: 'Stavern (Larvik), Vestfold',
    type: 'Commercial',
    format: 'Floating',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — Skagerrak',
    priceRange: '~250–400 NOK',
    bookingModel: 'Private hire',
    yearEst: 'c.2022',
    notes: 'Larvik municipality, Skagerrak coast.',
    website: '',
    isMultiSite: false,
    priority: 'medium',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'skagerrak', 'vestfold'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'kragero-badstuforening',
    vertical: 'sauna',
    name: 'Kragerø Badstuforening',
    region: 'Eastern Norway',
    subRegion: 'Kragerø, Telemark',
    type: 'Association / Non-profit',
    format: 'Floating raft',
    ownershipModel: 'Non-profit',
    waterAccess: 'Yes — Skagerrak',
    priceRange: '~100–200 NOK',
    bookingModel: 'Drop-in + members',
    yearEst: 'c.2020',
    notes: 'Association model. Telemark coast archipelago.',
    website: '',
    isMultiSite: false,
    priority: 'low',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'non-profit', 'telemark'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'hvaler-badstuforening',
    vertical: 'sauna',
    name: 'Hvaler Badstuforening',
    region: 'Eastern Norway',
    subRegion: 'Hvaler, Viken',
    type: 'Association / Non-profit',
    format: 'Floating',
    ownershipModel: 'Non-profit',
    waterAccess: 'Yes — Skagerrak',
    priceRange: '~100–150 NOK',
    bookingModel: 'Drop-in + members',
    yearEst: 'c.2021',
    notes: 'Hvaler archipelago near Swedish border.',
    website: '',
    isMultiSite: false,
    priority: 'low',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'non-profit', 'viken'],
    contact: { contactSource: 'research_needed' },
  },
  // ── EASTERN NORWAY — INNLANDET ─────────────────────────────
  {
    id: 'badstufergen',
    vertical: 'sauna',
    name: 'Badstufergen',
    region: 'Eastern Norway',
    subRegion: 'Lillehammer, Innlandet',
    type: 'Commercial',
    format: 'Floating (converted ferry)',
    ownershipModel: 'Private company',
    waterAccess: "Yes — Lake Mjøsa",
    priceRange: '~300–500 NOK',
    bookingModel: 'Private hire',
    yearEst: 'c.2020',
    notes: "Converted ferry sauna on Norway's largest lake.",
    website: '',
    isMultiSite: false,
    priority: 'medium',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'lake', 'innlandet', 'unique-format'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'kok-mjosa',
    vertical: 'sauna',
    name: 'KOK Mjøsa',
    region: 'Eastern Norway',
    subRegion: 'Hamar, Innlandet',
    type: 'Commercial',
    format: 'Floating sauna boat',
    ownershipModel: 'Private company (KOK brand)',
    waterAccess: 'Yes — Lake Mjøsa',
    priceRange: '~320–3,700 NOK',
    bookingModel: 'Drop-in + Private hire',
    yearEst: 'c.2022',
    notes: 'Sister operation to KOK Oslo on Lake Mjøsa at Hamar.',
    website: 'koknorge.no',
    isMultiSite: true,
    priority: 'high',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'lake', 'innlandet', 'multi-site', 'kok-brand'],
    estimatedValuation: 'EUR 3–6M (combined with KOK Oslo)',
    contact: {
      email: 'bedrift@koknorge.no',
      phone: '+47 934 00 522',
      address: 'C/O Mesh, Tordenskiolds gate 2, 0160 Oslo',
      contactSource: 'website',
    },
  },
  {
    id: 'flyt-fjordsauna',
    vertical: 'sauna',
    name: 'Flyt Fjordsauna',
    region: 'Eastern Norway',
    subRegion: 'Jevnaker, Innlandet',
    type: 'Commercial',
    format: 'Floating raft',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — Randsfjorden',
    priceRange: '~250–400 NOK',
    bookingModel: 'Private hire',
    yearEst: 'c.2021',
    notes: 'Randsfjorden lake. Wood-fired.',
    website: '',
    isMultiSite: false,
    priority: 'medium',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'lake', 'innlandet'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'glod-badstue',
    vertical: 'sauna',
    name: 'Glod Badstue / Glod Sauna',
    region: 'Eastern Norway',
    subRegion: 'Innlandet / Viken (lake)',
    type: 'Commercial',
    format: 'Land-based barrel',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — lake',
    priceRange: '~250–400 NOK',
    bookingModel: 'Private hire',
    yearEst: 'c.2021',
    notes: 'Intimate nature-facing barrel sauna. Fire pre-lit on arrival.',
    website: '',
    isMultiSite: false,
    priority: 'medium',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['land-based', 'barrel', 'innlandet', 'nature'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'spreke-opplevelser',
    vertical: 'sauna',
    name: 'Spreke Opplevelser',
    region: 'Eastern Norway',
    subRegion: 'Innlandet',
    type: 'Commercial',
    format: 'Land-based (barrel, nature)',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — lake/river',
    priceRange: 'Package pricing',
    bookingModel: 'Package / Private hire',
    yearEst: 'c.2020',
    notes: 'Sauna combined with guided outdoor/nature activities + winter swimming.',
    website: '',
    isMultiSite: false,
    priority: 'medium',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['land-based', 'barrel', 'innlandet', 'nature', 'activities'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'mirror-sauna',
    vertical: 'sauna',
    name: 'Mirror Sauna',
    region: 'Eastern Norway',
    subRegion: 'Telemark',
    type: 'Commercial',
    format: 'Land-based (barrel, mirrored)',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — lake',
    priceRange: '~300–500 NOK',
    bookingModel: 'Private hire',
    yearEst: 'c.2022',
    notes: 'Mirror-clad barrel sauna. Landmark structure in Telemark forest.',
    website: '',
    isMultiSite: false,
    priority: 'medium',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['land-based', 'barrel', 'telemark', 'design', 'landmark'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'eldmolla-sauna',
    vertical: 'sauna',
    name: 'Eldmølla Sauna',
    region: 'Eastern Norway',
    subRegion: 'Innlandet (forest/pond)',
    type: 'Commercial',
    format: 'Land-based (forest / barrel)',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — natural pond',
    priceRange: '~200–350 NOK',
    bookingModel: 'Private hire',
    yearEst: '2024',
    notes: 'Norwegian Sauna Association Newcomer of Year 2025. Cold dip in zinc tubs + oak barrels. Fairy-tale forest.',
    website: '',
    isMultiSite: false,
    priority: 'medium',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['land-based', 'barrel', 'innlandet', 'award-winning', 'new'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'hoyasen-sauna',
    vertical: 'sauna',
    name: 'Høyåsen Sauna',
    region: 'Eastern Norway',
    subRegion: 'Innlandet (historic farm)',
    type: 'Commercial',
    format: 'Land-based (historic farm cabin)',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — outdoor cold dip',
    priceRange: '~200–350 NOK',
    bookingModel: 'Private hire',
    yearEst: 'c.2022',
    notes: '16th-century farm roots. Historic restored cabin + sauna rental.',
    website: '',
    isMultiSite: false,
    priority: 'low',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['land-based', 'innlandet', 'historic'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'eggedal-outdoor',
    vertical: 'sauna',
    name: 'Eggedal Outdoor Sauna',
    region: 'Eastern Norway',
    subRegion: 'Eggedal, Numedal',
    type: 'Commercial',
    format: 'Land-based barrel (remote)',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — river/lake',
    priceRange: '~200–300 NOK',
    bookingModel: 'Private hire',
    yearEst: 'c.2021',
    notes: 'Off-the-beaten-path. Numedal valley.',
    website: '',
    isMultiSite: false,
    priority: 'low',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['land-based', 'barrel', 'remote', 'innlandet'],
    contact: { contactSource: 'research_needed' },
  },
  // ── WESTERN NORWAY — BERGEN ────────────────────────────────
  {
    id: 'heit-bergen-marineholmen',
    vertical: 'sauna',
    name: 'Heit Bergen (Marineholmen)',
    region: 'Western Norway',
    subRegion: 'Bergen',
    type: 'Commercial',
    format: 'Floating raft',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — Bergen harbour',
    priceRange: '159–1,990 NOK',
    bookingModel: 'Drop-in + Private hire',
    yearEst: 'c.2019',
    notes: 'Primary site at Marineholmen. Wood-fired, 8–12 ppl. Also Laksevåg & Måseskjæret.',
    website: 'heitbergen.no',
    isMultiSite: true,
    priority: 'high',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'multi-site', 'bergen', 'premium', 'brand'],
    estimatedValuation: 'EUR 2–4M',
    contact: {
      email: 'post@heitbergen.no',
      contactSource: 'website',
    },
  },
  {
    id: 'heit-bergen-laksevag',
    vertical: 'sauna',
    name: 'Heit Bergen (Laksevåg)',
    region: 'Western Norway',
    subRegion: 'Bergen — Laksevåg',
    type: 'Commercial',
    format: 'Floating raft',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — Bergen harbour',
    priceRange: '159–1,990 NOK',
    bookingModel: 'Drop-in + Private hire',
    yearEst: 'c.2020',
    notes: 'Second Heit site across the harbour from city centre.',
    website: 'heitbergen.no',
    isMultiSite: true,
    priority: 'high',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'multi-site', 'bergen', 'heit-brand'],
    contact: {
      email: 'post@heitbergen.no',
      contactSource: 'website',
    },
  },
  {
    id: 'heit-bergen-maseskjaeret',
    vertical: 'sauna',
    name: 'Heit Bergen (Måseskjæret)',
    region: 'Western Norway',
    subRegion: 'Bergen — Måseskjæret',
    type: 'Commercial',
    format: 'Floating raft',
    ownershipModel: 'Private company',
    waterAccess: 'Yes',
    priceRange: '159–1,990 NOK',
    bookingModel: 'Drop-in + Private hire',
    yearEst: 'c.2022',
    notes: 'Third Heit site; newest location.',
    website: 'heitbergen.no',
    isMultiSite: true,
    priority: 'high',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'multi-site', 'bergen', 'heit-brand'],
    contact: {
      email: 'post@heitbergen.no',
      contactSource: 'website',
    },
  },
  {
    id: 'city-sauna-bergen',
    vertical: 'sauna',
    name: 'City Sauna Bergen',
    region: 'Western Norway',
    subRegion: 'Bergen — Damsgårdsveien',
    type: 'Commercial',
    format: 'Floating (moored)',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — Bergen waterway',
    priceRange: '150–4,200 NOK',
    bookingModel: 'Drop-in + Private hire + Sauna cruise',
    yearEst: 'c.2020',
    notes: '4.9-star Google rating; one of highest-rated in Norway. Cruise option 3,000 NOK.',
    website: 'citysauna.no',
    isMultiSite: false,
    priority: 'high',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'bergen', 'premium', 'top-rated'],
    estimatedValuation: 'EUR 1.5–3M',
    contact: {
      email: 'booking@citysauna.no',
      phone: '+47 414 03 982',
      ownerName: 'Tormod Fagerbakke / Tore Fagerbakke',
      orgNumber: '926033972',
      address: 'Solheimsgaten 3, 5058 Bergen',
      contactSource: 'website',
    },
  },
  {
    id: 'laugaren-bergen',
    vertical: 'sauna',
    name: 'Laugaren (Bergen Laugarlag)',
    region: 'Western Norway',
    subRegion: 'Bergen — Georgernes Verft',
    type: 'Association / Non-profit',
    format: 'Floating raft',
    ownershipModel: 'Non-profit (volunteer)',
    waterAccess: 'Yes — USF Verftet harbour',
    priceRange: '~100–150 NOK',
    bookingModel: 'Drop-in + members',
    yearEst: 'c.2019',
    notes: 'Community sauna. Strong civic ethos. Affordable drop-in.',
    website: '',
    isMultiSite: false,
    priority: 'low',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'non-profit', 'bergen'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'vestfjord-sauna',
    vertical: 'sauna',
    name: 'Vestfjord Sauna',
    region: 'Western Norway',
    subRegion: 'Bergen — Kjøkkelvik',
    type: 'Commercial',
    format: 'Land-based (shore-side)',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — sea',
    priceRange: '198–219 NOK',
    bookingModel: 'Drop-in + Private hire',
    yearEst: 'c.2022',
    notes: 'Himalayan salt wall. Shore-based. 06:00–23:00 daily. Founded by Fredrik Lie-Helgesen (Oceanvs Head of Platform).',
    website: 'vestfjordsauna.no',
    isMultiSite: false,
    priority: 'high',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['land-based', 'bergen', 'oceanvs-connected', 'anchor-asset'],
    estimatedValuation: 'EUR 1–2M',
    contact: {
      ownerName: 'Fredrik Lie-Helgesen',
      contactSource: 'manual',
    },
  },
  // ── WESTERN NORWAY — FJORDS ────────────────────────────────
  {
    id: 'fjordsauna-flam',
    vertical: 'sauna',
    name: 'FjordSauna Flåm',
    region: 'Western Norway',
    subRegion: 'Flåm, Vestland',
    type: 'Commercial',
    format: 'Floating (moored)',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — Aurlandsfjord',
    priceRange: '250–2,990 NOK',
    bookingModel: 'Drop-in + Private hire',
    yearEst: 'c.2019',
    notes: 'Electric. Up to 12 ppl. Fjord-floor hatch for plunge. UNESCO fjord setting.',
    website: 'fjordsauna.com',
    isMultiSite: true,
    priority: 'high',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'unesco', 'fjord', 'multi-site', 'premium', 'tourist-facing'],
    estimatedValuation: 'EUR 2–4M',
    contact: {
      email: 'mail@fjordsauna.com',
      phone: '+47 960 05 305',
      address: 'Postboks 50, 5742 Flåm',
      orgNumber: '934 924 142',
      contactSource: 'website',
    },
  },
  {
    id: 'fjordsauna-aurland',
    vertical: 'sauna',
    name: 'FjordSauna Aurland',
    region: 'Western Norway',
    subRegion: 'Aurland, Vestland',
    type: 'Commercial',
    format: 'Floating (moored)',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — Aurlandsfjord',
    priceRange: '250–2,990 NOK',
    bookingModel: 'Drop-in + Private hire',
    yearEst: 'c.2020',
    notes: 'Sister operation to Flåm FjordSauna. Same UNESCO fjord branch.',
    website: 'fjordsauna.com',
    isMultiSite: true,
    priority: 'high',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'unesco', 'fjord', 'multi-site', 'premium', 'fjordsauna-brand'],
    contact: {
      email: 'mail@fjordsauna.com',
      phone: '+47 960 05 305',
      address: 'Postboks 50, 5742 Flåm',
      orgNumber: '934 924 142',
      contactSource: 'website',
    },
  },
  {
    id: 'hardanger-flytebadstu',
    vertical: 'sauna',
    name: 'Hardanger Flytebadstu',
    region: 'Western Norway',
    subRegion: 'Ulvik, Hardangerfjord',
    type: 'Commercial',
    format: 'Floating raft',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — Hardangerfjord',
    priceRange: '~300–500 NOK',
    bookingModel: 'Private hire',
    yearEst: 'c.2021',
    notes: 'Orchard valley fjord setting. Drama of Hardangerfjord walls.',
    website: '',
    isMultiSite: false,
    priority: 'medium',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'hardangerfjord', 'scenic'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'os-sauna',
    vertical: 'sauna',
    name: 'Os Sauna',
    region: 'Western Norway',
    subRegion: 'Os (Bjørnafjorden), Vestland',
    type: 'Commercial',
    format: 'Floating',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — fjord/coast',
    priceRange: '~250–400 NOK',
    bookingModel: 'Drop-in + Private hire',
    yearEst: 'c.2021',
    notes: 'Just south of Bergen.',
    website: '',
    isMultiSite: false,
    priority: 'medium',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'vestland'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'dampen-fjaerland',
    vertical: 'sauna',
    name: 'Dampen Sauna Fjaerland',
    region: 'Western Norway',
    subRegion: 'Fjærland, Vestland',
    type: 'Commercial',
    format: 'Floating (moored)',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — Fjærlandsfjord/glacier',
    priceRange: '~250–400 NOK',
    bookingModel: 'Private hire',
    yearEst: 'c.2021',
    notes: 'Glacier-view setting. Wood-fired. Partner with Fjærland Guiding.',
    website: '',
    isMultiSite: false,
    priority: 'medium',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'glacier', 'vestland', 'scenic'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'elvatun-friluftsspa',
    vertical: 'sauna',
    name: 'Elvatun Friluftsspa',
    region: 'Western Norway',
    subRegion: 'Inner Vestland (river valley)',
    type: 'Commercial',
    format: 'Land-based barrel',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — river',
    priceRange: '~250–400 NOK',
    bookingModel: 'Private hire',
    yearEst: 'c.2021',
    notes: 'River cold plunge. Barrel form in rustic valley surroundings.',
    website: '',
    isMultiSite: false,
    priority: 'medium',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['land-based', 'barrel', 'river', 'vestland'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'kinn-damp',
    vertical: 'sauna',
    name: 'Kinn Damp',
    region: 'Western Norway',
    subRegion: 'Florø, Vestland',
    type: 'Commercial',
    format: 'Floating / Coastal',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — Atlantic/open coast',
    priceRange: '~250–400 NOK',
    bookingModel: 'Private hire',
    yearEst: 'c.2021',
    notes: 'Open Atlantic coast. One of westernmost sauna operators in Norway.',
    website: '',
    isMultiSite: false,
    priority: 'medium',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'atlantic', 'vestland', 'remote'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'sjobris-sauna',
    vertical: 'sauna',
    name: 'Sjøbris Sauna',
    region: 'Western Norway',
    subRegion: 'Ørsta, Sunnmøre',
    type: 'Commercial',
    format: 'Floating / land-based',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — fjord',
    priceRange: '~200–350 NOK',
    bookingModel: 'Drop-in + Private hire',
    yearEst: 'c.2022',
    notes: 'Sunnmøre region, Ørsta.',
    website: '',
    isMultiSite: false,
    priority: 'medium',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'sunnmøre'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'lidasanden',
    vertical: 'sauna',
    name: 'Lidasanden Flytende Badstu',
    region: 'Western Norway',
    subRegion: 'Stryn, Nordfjord',
    type: 'Commercial',
    format: 'Floating raft',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — fjord',
    priceRange: '~200–350 NOK',
    bookingModel: 'Private hire',
    yearEst: 'c.2022',
    notes: 'Nordfjord region, Stryn.',
    website: '',
    isMultiSite: false,
    priority: 'medium',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'nordfjord'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'fjelg-sauna',
    vertical: 'sauna',
    name: 'Fjelg Sauna / Fjolg Sauna',
    region: 'Western Norway',
    subRegion: 'Outer Vestland coast',
    type: 'Commercial',
    format: 'Land-based barrel (coastal)',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — Atlantic coast',
    priceRange: '~250–400 NOK',
    bookingModel: 'Private hire',
    yearEst: 'c.2022',
    notes: 'Twin operations; outer coast Atlantic exposure. Cold and elemental.',
    website: '',
    isMultiSite: true,
    priority: 'medium',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['land-based', 'barrel', 'atlantic', 'vestland', 'twin'],
    contact: { contactSource: 'research_needed' },
  },
  // ── WESTERN NORWAY — ÅLESUND & ROGALAND ───────────────────
  {
    id: 'pulpit-sauna',
    vertical: 'sauna',
    name: 'Pulpit Sauna (Jørpeland)',
    region: 'Western Norway',
    subRegion: 'Jørpeland, Rogaland',
    type: 'Commercial',
    format: 'Floating (moored)',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — Lysefjord/lake',
    priceRange: '~250–500 NOK',
    bookingModel: 'Private hire',
    yearEst: 'c.2020',
    notes: 'At foot of Preikestolen (Pulpit Rock) hike. Distinctive post-hike pairing.',
    website: '',
    isMultiSite: false,
    priority: 'high',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'lysefjord', 'tourism', 'scenic', 'preikestolen'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'svai-sauna',
    vertical: 'sauna',
    name: 'SVAI Sauna Ålesund',
    region: 'Western Norway',
    subRegion: 'Ålesund, Møre og Romsdal',
    type: 'Commercial',
    format: 'Floating (moored)',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — Brosundet / Atlantic',
    priceRange: '250–2,500 NOK',
    bookingModel: 'Drop-in + Private hire',
    yearEst: 'c.2020',
    notes: 'Molja harbour. Fish-drying rack design. Panoramic Atlantic views. 10:00–22:00.',
    website: 'svaisauna.no',
    isMultiSite: false,
    priority: 'high',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'ålesund', 'design', 'atlantic', 'premium'],
    estimatedValuation: 'EUR 1–2M',
    contact: { contactSource: 'research_needed', email: 'post@svaisauna.no' },
  },
  {
    id: 'damp-storhaug',
    vertical: 'sauna',
    name: 'Damp Sauna Storhaug',
    region: 'Western Norway',
    subRegion: 'Stavanger — Storhaug',
    type: 'Commercial',
    format: 'Floating (fleet)',
    ownershipModel: 'Private company (Damp brand)',
    waterAccess: 'Yes — Gandsfjorden/harbour',
    priceRange: '~225–300+ NOK',
    bookingModel: 'Private hire',
    yearEst: 'c.2021',
    notes: 'Cluster of small Damp boats at Storhaug waterfront. Most competitive micro-market in Norway.',
    website: '',
    isMultiSite: true,
    priority: 'high',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'stavanger', 'fleet', 'damp-brand', 'multi-site'],
    estimatedValuation: 'EUR 2–4M (full Damp brand)',
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'booksauna-otto',
    vertical: 'sauna',
    name: 'BookSauna Otto / Vaulen',
    region: 'Western Norway',
    subRegion: 'Stavanger — Vaulen',
    type: 'Commercial',
    format: 'Floating raft',
    ownershipModel: 'Platform (BookSauna model)',
    waterAccess: 'Yes — Gandsfjorden',
    priceRange: '225–300 NOK',
    bookingModel: 'Private hire only',
    yearEst: 'c.2020',
    notes: 'Min 4 ppl charge. SUP boards included. One of highest-rated in Stavanger.',
    website: 'booksauna.no',
    isMultiSite: false,
    priority: 'medium',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'stavanger', 'platform-model'],
    contact: {
      email: 'post@booksauna.no',
      orgNumber: '831 938 692',
      contactSource: 'website',
    },
  },
  {
    id: 'tananger-sauna',
    vertical: 'sauna',
    name: 'Tananger Floating Sauna',
    region: 'Western Norway',
    subRegion: 'Tananger (Sola), Rogaland',
    type: 'Commercial',
    format: 'Floating (moored at hotel jetty)',
    ownershipModel: 'Private company (Hummeren)',
    waterAccess: 'Yes — North Sea coast',
    priceRange: '~500+ NOK',
    bookingModel: 'Private hire only',
    yearEst: 'c.2020',
    notes: 'Affiliated with Hummeren Hotel jetty but sold as standalone sauna experience. 6–8 ppl.',
    website: 'hummeren.no',
    isMultiSite: false,
    priority: 'medium',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'rogaland', 'hotel-affiliated', 'north-sea'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'damp-isla',
    vertical: 'sauna',
    name: 'Damp Isla / Damp Lohui / Damp Sanna',
    region: 'Western Norway',
    subRegion: 'Stavanger / Rogaland',
    type: 'Commercial',
    format: 'Floating (barrel design fleet)',
    ownershipModel: 'Private company (Damp brand)',
    waterAccess: 'Yes',
    priceRange: '~225–350 NOK',
    bookingModel: 'Private hire',
    yearEst: 'c.2021',
    notes: 'Design-forward Damp fleet; each unit named individually. Barrel architecture on water.',
    website: '',
    isMultiSite: true,
    priority: 'high',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'stavanger', 'fleet', 'damp-brand', 'design'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'kur-sauna-ula',
    vertical: 'sauna',
    name: 'Kur Sauna Ula',
    region: 'Western Norway',
    subRegion: 'Jæren coast, Rogaland',
    type: 'Commercial',
    format: 'Land-based barrel (coastal)',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — North Sea / Jæren coast',
    priceRange: '~250–400 NOK',
    bookingModel: 'Private hire',
    yearEst: 'c.2022',
    notes: 'Elemental setting on flat wind-scoured Jæren shore.',
    website: '',
    isMultiSite: false,
    priority: 'medium',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['land-based', 'barrel', 'jæren', 'rogaland'],
    contact: { contactSource: 'research_needed' },
  },
  // ── SOUTHERN NORWAY ────────────────────────────────────────
  {
    id: 'blaud-sauna',
    vertical: 'sauna',
    name: 'Blaud Sauna',
    region: 'Southern Norway',
    subRegion: 'Kristiansand',
    type: 'Commercial',
    format: 'Floating',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — Skagerrak',
    priceRange: '~250–400 NOK',
    bookingModel: 'Private hire',
    yearEst: 'c.2021',
    notes: "Norway's southernmost city. Capacity ~10 ppl.",
    website: '',
    isMultiSite: false,
    priority: 'medium',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'skagerrak', 'kristiansand'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'damp-kata',
    vertical: 'sauna',
    name: 'Damp Kata',
    region: 'Southern Norway',
    subRegion: 'Arendal, Aust-Agder',
    type: 'Commercial',
    format: 'Floating (Damp boat)',
    ownershipModel: 'Private company (Damp brand)',
    waterAccess: 'Yes — Skagerrak inlet',
    priceRange: '~200–350 NOK',
    bookingModel: 'Private hire',
    yearEst: 'c.2021',
    notes: 'Damp fleet boat. Calm Skagerrak setting.',
    website: '',
    isMultiSite: false,
    priority: 'medium',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'damp-brand', 'skagerrak'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'damp-fevik',
    vertical: 'sauna',
    name: 'Damp Fevik',
    region: 'Southern Norway',
    subRegion: 'Grimstad, Aust-Agder',
    type: 'Commercial',
    format: 'Floating (Damp boat)',
    ownershipModel: 'Private company (Damp brand)',
    waterAccess: 'Yes — Skagerrak',
    priceRange: '~200–350 NOK',
    bookingModel: 'Private hire',
    yearEst: 'c.2022',
    notes: 'Perfect 5-star Google rating. Near Grimstad.',
    website: '',
    isMultiSite: false,
    priority: 'medium',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'damp-brand', 'skagerrak', 'top-rated'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'badstubaten-pysen',
    vertical: 'sauna',
    name: 'Badstubåten Pysen',
    region: 'Southern Norway',
    subRegion: 'Mandal, Vest-Agder',
    type: 'Commercial',
    format: 'Floating sauna boat',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — Skagerrak/Mandal river',
    priceRange: '~250–400 NOK',
    bookingModel: 'Private hire',
    yearEst: 'c.2021',
    notes: "Mandal, Norway's southernmost town area.",
    website: '',
    isMultiSite: false,
    priority: 'medium',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'skagerrak', 'mandal'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'homborsauna',
    vertical: 'sauna',
    name: 'Homborsauna',
    region: 'Southern Norway',
    subRegion: 'Grimstad, Aust-Agder',
    type: 'Commercial',
    format: 'Floating / land-based coastal',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — Skagerrak',
    priceRange: '~200–350 NOK',
    bookingModel: 'Drop-in + Private hire',
    yearEst: 'c.2022',
    notes: 'Grimstad area.',
    website: '',
    isMultiSite: false,
    priority: 'medium',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'skagerrak', 'grimstad'],
    contact: { contactSource: 'research_needed' },
  },
  // ── CENTRAL NORWAY — TRONDHEIM ─────────────────────────────
  {
    id: 'stu-brattora',
    vertical: 'sauna',
    name: 'Stu Brattøra',
    region: 'Central Norway',
    subRegion: 'Trondheim',
    type: 'Commercial',
    format: 'Floating (moored)',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — Trondheimsfjord',
    priceRange: '~200–400 NOK',
    bookingModel: 'Drop-in + Private hire',
    yearEst: 'c.2020',
    notes: 'Behind Trondheim central station. Walkable from cruise terminal. Very convenient.',
    website: '',
    isMultiSite: false,
    priority: 'high',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'trondheim', 'central-location', 'tourism'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'damp-trondja',
    vertical: 'sauna',
    name: 'Damp Trondja',
    region: 'Central Norway',
    subRegion: 'Trondheim',
    type: 'Commercial',
    format: 'Floating (Damp boat)',
    ownershipModel: 'Private company (Damp brand)',
    waterAccess: 'Yes — Trondheimsfjord',
    priceRange: '~200–350 NOK',
    bookingModel: 'Drop-in + Private hire',
    yearEst: 'c.2021',
    notes: 'Central Trondheim harbour. Short walk from Stu Brattøra.',
    website: '',
    isMultiSite: false,
    priority: 'medium',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'trondheim', 'damp-brand'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'kristiansund-floating',
    vertical: 'sauna',
    name: 'Kristiansund Floating Sauna',
    region: 'Central Norway',
    subRegion: 'Kristiansund, Møre og Romsdal',
    type: 'Commercial',
    format: 'Floating',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — Atlantic coast',
    priceRange: '~200–400 NOK',
    bookingModel: 'Private hire',
    yearEst: 'c.2022',
    notes: 'Fishing harbour setting.',
    website: '',
    isMultiSite: false,
    priority: 'medium',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'atlantic', 'møre-og-romsdal'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'havna-sjobad',
    vertical: 'sauna',
    name: 'Havna Sjøbad',
    region: 'Central Norway',
    subRegion: 'Namsos, Trøndelag',
    type: 'Commercial',
    format: 'Floating / waterfront',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — Namsenfjord',
    priceRange: '~200–350 NOK',
    bookingModel: 'Drop-in + Private hire',
    yearEst: 'c.2022',
    notes: 'Small fishing harbour town. Among working boats.',
    website: '',
    isMultiSite: false,
    priority: 'medium',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'trøndelag', 'harbour'],
    contact: { contactSource: 'research_needed' },
  },
  // ── NORTHERN NORWAY ────────────────────────────────────────
  {
    id: 'pust-tromso',
    vertical: 'sauna',
    name: 'Pust Tromsø',
    region: 'Northern Norway',
    subRegion: 'Tromsø',
    type: 'Commercial',
    format: 'Floating platform (2 rooms)',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — Arctic Ocean/harbour',
    priceRange: '120–3,000 NOK',
    bookingModel: 'Drop-in + Private hire + Rituals',
    yearEst: 'c.2018',
    notes: "2 rooms: Original (12 ppl) + Lavvo (16 ppl). Aufguss rituals, 'Ice Bath Viking' package. Multiple locations across Norway.",
    website: 'pust.io',
    isMultiSite: true,
    priority: 'high',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'tromsø', 'arctic', 'premium', 'multi-site', 'brand', 'wellness'],
    estimatedValuation: 'EUR 3–6M',
    contact: {
      email: 'hello@pust.io',
      contactSource: 'website',
    },
  },
  {
    id: 'vulkana',
    vertical: 'sauna',
    name: 'Vulkana',
    region: 'Northern Norway',
    subRegion: 'Tromsø',
    type: 'Commercial',
    format: 'Floating (converted vessel, mobile)',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — Arctic Ocean',
    priceRange: '~500–2,000+ NOK',
    bookingModel: 'Private cruise / Private hire',
    yearEst: 'c.2016',
    notes: 'Genuinely mobile; sails to different fjord arms during session. Wood-fired. One of most photographed wellness vessels in Norway.',
    website: '',
    isMultiSite: false,
    priority: 'high',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'tromsø', 'arctic', 'premium', 'mobile', 'unique-format', 'iconic'],
    estimatedValuation: 'EUR 1.5–3M',
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'lofoten-sauna-svinoya',
    vertical: 'sauna',
    name: 'Lofoten Sauna Svinøya',
    region: 'Northern Norway',
    subRegion: 'Svolvær, Lofoten',
    type: 'Commercial',
    format: 'Floating (moored at rorbu)',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — Vestfjord',
    priceRange: '250+ NOK',
    bookingModel: 'Private hire',
    yearEst: 'c.2019',
    notes: 'Among historic rorbu fishing cabins. Svolværgeita peak backdrop.',
    website: '',
    isMultiSite: false,
    priority: 'high',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'lofoten', 'arctic', 'tourism', 'heritage'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'lofoten-beach-camp',
    vertical: 'sauna',
    name: 'Lofoten Beach Camp Sauna',
    region: 'Northern Norway',
    subRegion: 'Flakstad, Lofoten',
    type: 'Commercial',
    format: 'Land-based (beach-side)',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — Arctic beach',
    priceRange: '~250–400 NOK',
    bookingModel: 'Private hire',
    yearEst: 'c.2021',
    notes: 'White-sand Lofoten beach. Heat → run across sand → plunge.',
    website: '',
    isMultiSite: false,
    priority: 'medium',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['land-based', 'lofoten', 'arctic', 'beach'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'hov-sauna',
    vertical: 'sauna',
    name: 'Hov Sauna',
    region: 'Northern Norway',
    subRegion: 'Gimsøya, Lofoten',
    type: 'Commercial',
    format: 'Land-based outdoor (beach)',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — Arctic beach / sea',
    priceRange: '~250–400 NOK',
    bookingModel: 'Private hire',
    yearEst: 'c.2022',
    notes: 'Hidden option on quieter Gimsøya island. White sand + turquoise Arctic water.',
    website: '',
    isMultiSite: false,
    priority: 'medium',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['land-based', 'lofoten', 'arctic', 'beach'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'skarungen-spa',
    vertical: 'sauna',
    name: 'Skårungen Spa Pier',
    region: 'Northern Norway',
    subRegion: 'Svolvær, Lofoten',
    type: 'Commercial',
    format: 'Land-based (sauna pier / hot tub)',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — Vestfjord',
    priceRange: '250–399 NOK',
    bookingModel: 'Private hire (exclusive)',
    yearEst: '2024 (renovated)',
    notes: 'Hot tub + sauna pier. 8–10 ppl hot tub + 10–12 ppl sauna. Views to Vågekallen mt.',
    website: '',
    isMultiSite: false,
    priority: 'medium',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['land-based', 'lofoten', 'premium', 'pier'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'kleksen-saunaboat',
    vertical: 'sauna',
    name: 'Kleksen Saunaboat',
    region: 'Northern Norway',
    subRegion: 'Narvik, Nordland',
    type: 'Commercial',
    format: 'Floating sauna boat (wood-fired)',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — Ofotfjord',
    priceRange: '~300–500 NOK',
    bookingModel: 'Private hire',
    yearEst: 'c.2021',
    notes: 'One of highest Google ratings for any floating sauna in Norway. ~12 ppl.',
    website: '',
    isMultiSite: false,
    priority: 'high',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'narvik', 'arctic', 'top-rated', 'nordland'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'varanger-brygge',
    vertical: 'sauna',
    name: 'Varanger Brygge',
    region: 'Northern Norway',
    subRegion: 'Bugøynes, Finnmark',
    type: 'Commercial',
    format: 'Floating / land-based waterfront',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — Varangerfjord',
    priceRange: '~250–400 NOK',
    bookingModel: 'Private hire',
    yearEst: 'c.2020',
    notes: 'Far northeast; near Russian border. Wood-fired. Extremely remote.',
    website: '',
    isMultiSite: false,
    priority: 'low',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'finnmark', 'arctic', 'remote'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'varanger-view',
    vertical: 'sauna',
    name: 'Varanger View',
    region: 'Northern Norway',
    subRegion: 'Vardø, Finnmark',
    type: 'Commercial',
    format: 'Floating / coastal',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — Barents Sea',
    priceRange: '~250–400 NOK',
    bookingModel: 'Private hire',
    yearEst: 'c.2021',
    notes: 'Vardø — among most remote sauna ops in Norway. Aurora/king-crab season.',
    website: '',
    isMultiSite: false,
    priority: 'low',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'finnmark', 'arctic', 'remote', 'aurora'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'ahpi-flytende',
    vertical: 'sauna',
    name: 'Áhpi Flytende Badstue',
    region: 'Northern Norway',
    subRegion: 'Skjervøy, Troms',
    type: 'Commercial',
    format: 'Floating',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — Kvænangen fjord',
    priceRange: '~200–350 NOK',
    bookingModel: 'Drop-in + Private hire',
    yearEst: 'c.2022',
    notes: 'Deep into Troms county, above Arctic Circle.',
    website: '',
    isMultiSite: false,
    priority: 'low',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'troms', 'arctic'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'bugoynes-opplevelser',
    vertical: 'sauna',
    name: 'Bugøynes Opplevelser',
    region: 'Northern Norway',
    subRegion: 'Bugøynes, Finnmark',
    type: 'Commercial',
    format: 'Land-based barrel (Arctic coastal)',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — Varangerfjord',
    priceRange: '~250–400 NOK',
    bookingModel: 'Private hire / Experience package',
    yearEst: 'c.2020',
    notes: 'Barrel sauna in far northeast. Most remote barrel experience in Norway.',
    website: '',
    isMultiSite: false,
    priority: 'low',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['land-based', 'barrel', 'finnmark', 'arctic', 'remote'],
    contact: { contactSource: 'research_needed' },
  },
  {
    id: 'svalbad-svalbard',
    vertical: 'sauna',
    name: 'SvalBad Svalbard',
    region: 'Northern Norway',
    subRegion: 'Longyearbyen, Svalbard',
    type: 'Commercial',
    format: 'Floating',
    ownershipModel: 'Private company',
    waterAccess: 'Yes — Arctic Ocean (78°N)',
    priceRange: '~500+ NOK',
    bookingModel: 'Private hire',
    yearEst: 'c.2022',
    notes: '78° North. Rarest operating location in Norway. Polar wilderness.',
    website: '',
    isMultiSite: false,
    priority: 'medium',
    stage: 'prospect',
    outreachNotes: [],
    tags: ['floating', 'svalbard', 'arctic', 'premium', 'unique-location'],
    contact: { contactSource: 'research_needed' },
  },
]

// ── HELPERS ────────────────────────────────────────────────────

export function getHighPriorityTargets(): SaunaOperator[] {
  return SAUNA_OPERATORS.filter(
    op => op.priority === 'high' && op.type === 'Commercial'
  )
}

export function getMultiSiteOperators(): SaunaOperator[] {
  return SAUNA_OPERATORS.filter(op => op.isMultiSite)
}

export function getOperatorsByRegion(region: string): SaunaOperator[] {
  return SAUNA_OPERATORS.filter(op => op.region === region)
}

export function getCommercialOperators(): SaunaOperator[] {
  return SAUNA_OPERATORS.filter(op => op.type === 'Commercial')
}
